### ISSUE TITLE
设备相关问题

### ISSUE THREAD

**Issue by qqxuzeman** [winxos/question-helper#1]
你好，请问使用的摄像头有没有品牌推荐

**Comment by qqxuzeman** [comment]
支架也推荐一下，我对您的设备很感兴趣

**Comment by winxos** [comment]
> 支架也推荐一下，我对您的设备很感兴趣

支架不重要，我随便找了个以前的3d打印的架子弄的，自己随便筷子搭个都行，有条件的话3d打印一个比较完美，只要保证视野范围主要是题目就行，ocr的识别率是很高的。

**Comment by winxos** [comment]
> 你好，请问使用的摄像头有没有品牌推荐

设备并无特殊要求，普通usb摄像头就可以了，清晰度够就行。
