### ISSUE TITLE
关于代码问题

### ISSUE THREAD

**Issue by qqxuzeman** [winxos/question-helper#2]
1、find_question中的logger.info("new question:%f,%s",v, res) 中，res似乎没有变量；

**Comment by qqxuzeman** [comment]
成功运行了，在此感谢你。下面的的代码我注释了
 # temp = np.asarray(img)
 # temp = temp.reshape((SCREEN_HEIGHT, SCREEN_WIDTH, 3))

主函数中最后的代码运行中出现了报错，目前我是注释了，报错如下
ValueError: cannot reshape array of size 1221120 into shape ；是否跟我用的是GPU版本的有关

**Comment by winxos** [comment]
> 1、find_question中的logger.info("new question:%f,%s",v, res) 中，res似乎没有变量；

这个问题是升级过程中的手误，后面修复了。

**Comment by winxos** [comment]
> 成功运行了，在此感谢你。下面的的代码我注释了
> 
> # temp = np.asarray(img)
> # temp = temp.reshape((SCREEN_HEIGHT, SCREEN_WIDTH, 3))
> 主函数中最后的代码运行中出现了报错，目前我是注释了，报错如下 ValueError: cannot reshape array of size 1221120 into shape ；是否跟我用的是GPU版本的有关

这个错误应该是摄像头默认分辨率的问题，你的摄像头可能不支持800x600的分辨率，可以实际查看自己摄像头分辨率，然后把这个值设置为自己摄像头使用的分辨率。
